const router = require('express').Router()

const goalHalfFull = require('../controllers/goal/halfFull')
const goalOverUnder = require('../controllers/goal/overUnder')
const goalBtts = require('../controllers/goal/bothTeamsToScore')
const goalPerfil = require('../controllers/goal/info')

router.get('/fulltime', goalHalfFull.fullTime)
router.get('/fulltime/:team/:latest', goalHalfFull.latestFT)
router.get('/fulltime/home', goalHalfFull.fullTimeHome)
router.get('/fulltime/home/:team/:latest', goalHalfFull.latestFullHome)
router.get('/fulltime/away', goalHalfFull.fullTimeAway)
router.get('/fulltime/away/:team/:latest', goalHalfFull.latestFullAway)
router.get('/halftime', goalHalfFull.halftime)
router.get('/halftime/:team/:latest', goalHalfFull.latestHT)
router.get('/halftime/home', goalHalfFull.homeHT)
router.get('/halftime/home/:team/:latest', goalHalfFull.latestHomeHT)
router.get('/halftime/away', goalHalfFull.awayHT)
router.get('/halftime/away/:team/:latest', goalHalfFull.latestAwayHT)
router.get('/overunder/ft', goalOverUnder.OverUnderFT)
router.get('/overunder/ft/:team/:latest', goalOverUnder.latestOverUnderFT)
router.get('/overunder/ht', goalOverUnder.OverUnderHT)
router.get('/overunder/ht/:team/:latest', goalOverUnder.latestOverUnderHT)
router.get('/btts', goalBtts.btts)
router.get('/btts/:team/:latest', goalBtts.latestBtts)
router.get('/info/:team/:latest', goalPerfil.info)
router.get('/info/:teamHome/:teamAway/:latest', goalPerfil.compare)

module.exports = router